version: '3'

networks:
  service-net:
    external: false

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=consolidator
      - POSTGRES_USER=consolidator
      - POSTGRES_PASSWORD=consolidator
    ports:
      - "5432:5432"
    volumes:
      - ".docker/postgres:/var/lib/postgresql/data"
    networks:
      - service-net